name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  xcode:
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
        xcode:
          # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode
          - "10.3"
          - "11.2.1"
          - "11.3.1"
          - "11.4.1"
          - "11.5"
          - "11.6"
          - "11.7"
          - "12.0.1"
          - "12.1"
          - "12.1.1"
          - "12.2"
          - "12.3"
          - "12.4"
        include:
          # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode
          - os: macos-11
            xcode: "12.5.1"
          - os: macos-11
            xcode: "13.0"
          - os: macos-11
            xcode: "13.1"
          - os: macos-11
            xcode: "13.2"
          - os: macos-11
            xcode: "13.2.1"
          # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode
          - os: macos-12
            xcode: "13.3.1"
          - os: macos-12
            xcode: "13.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE:STRING=Debug
      - name: Build
        run: cmake --build build --config Debug
      - name: Test
        working-directory: build
        run: ctest --build-config Debug --output-on-failure
