name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  xcode:
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
        xcode:
          # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#xcode
          - "15.0.1"
          - "15.1"
          - "15.2"
          - "15.3"
          - "15.4"
          - "16.1"
          - "16.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE:STRING=Debug
      - name: Build
        run: cmake --build build --config Debug
      - name: Test
        working-directory: build
        run: ctest --build-config Debug --output-on-failure
