name: Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  msvc:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2019
          - 2022
        include:
          - version: 2019
            generator: "Visual Studio 16 2019"
          - version: 2022
            generator: "Visual Studio 17 2022"
    runs-on: windows-${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: cmake -S . -B build -G "${{ matrix.generator }}"
      - name: Build
        run: cmake --build build --config Debug
      - name: Test
        working-directory: build
        run: ctest --build-config Debug --output-on-failure
